### ISSUE TITLE
Make standalone CLI build work correctly

### ISSUE THREAD

**Issue by vsnthdev** [konsumer/crossaudio#2]
During compilation with the following command 👇

```
esbuild --platform=node --bundle --outfile=../../dist/cli/crossaudio.js crossaudio.js && pkg --no-bytecode --public --public-packages '*' --compress brotli --out-path ../../bin ../../dist/cli/crossaudio.js
```

The following two warnings appear 👇

![Screenshot 2021-07-19 at 8 22 32 AM](https://user-images.githubusercontent.com/24322511/126095920-714fa52e-d6e1-4c34-af65-8b7620e803f1.png)

Upon further inspection of the bundle generated by `esbuild`, it looks like `config.extends` originates from `yargs` package 👇

![Screenshot 2021-07-19 at 8 24 40 AM](https://user-images.githubusercontent.com/24322511/126096104-809d02ac-8a24-46ad-aa29-1f5be6ce3e70.png)

Replace `yargs` with another alternative like [commander.js](https://github.com/tj/commander.js) to fix the issue during compilation with `pkg`.

**Comment by konsumer** [comment]
The build stuff is in progress, but I will try commander. Pkg was having other problems that required build, so I started using esbuild (which didn't fix pkg building) so I might just drop both and instruct users to just install with npm (rather than try to build a standalone with pkg.) It's all very early work right now though. There may be some other good option like nexe or something. You can use it fine without building, now, though.

**Comment by konsumer** [comment]
Also, I'm not sure if commander can do the dynamic args stuff I am doing (to hook up midi to any param) but I am open to trying it out.

**Comment by konsumer** [comment]
One thing I was thinking about with this, as I was having stupid build issues, is maybe it just makes sense to require node 16 (for good esm support) and npm, because without them you won't be able to do anything that requires external modules from npm, or the es6 module syntax I use in the examples, which is sort of a lame experience, anyway. Like you sort of need node to use it anyway, and in that case, no build is needed.

**Comment by vasanthdeveloper** [comment]
If you want to ship a standalone executable, this is the right time to do it, that is when the project is still in development. Later you can't change the dependencies if they don't work with `pkg`.

Also, `pkg` is the most advanced and maintained packager right now. I've tried `nexe`, `nodec` which have even bigger problems, for example with `nexe` you have to compile newer builds of Node.js from source code yourself.

Regarding commander, I am expecting commander can do dynamic args, since it's a slightly bigger project 🤔

**Comment by vasanthdeveloper** [comment]
> One thing I was thinking about with this, as I was having stupid build issues, is maybe it just makes sense to require node 16 (for good esm support) and npm
Yes, the newer Node is the better ESM support we'll get.

> es6 module syntax I use in the examples, which is sort of a lame experience, anyway
That's because the entire JavaScript ecosystem is in the transition period of switching from CommonJS to ESM modules.

**Comment by konsumer** [comment]
> If you want to ship a standalone executable, this is the right time to do it, that is when the project is still in development. Later you can't change the dependencies if they don't work with pkg.

Maybe. It's trivial to add later (this is a thin wrapper around the lib) and I'd prefer to not support issues with it in beta, so it might not actually be the best time to spend a lot of time adding support, since just running from `bin` (installed with `npm install`) works fine, with no build. As crossaudio is in early beta, this seems like a more appropriate workflow, anyway (for beta testers that are familiar with the node ecosystem.)

> Also, pkg is the most advanced and maintained packager right now. I've tried nexe, nodec which have even bigger problems, for example with nexe you have to compile newer builds of Node.js from source code yourself.

Yeh, I have tried them all too. I like pkg when it works, but it has serious issues with dynamic imports (which this uses to load the user's synth) and also freaks on native module support (`type: module` in package.json.) It definitely requires commonjs polyfills for esm, which is annoying. esbuild is at least fast, so that's cool, but it's an annoying situation to begin with.

> Regarding commander, I am expecting commander can do dynamic args, since it's a slightly bigger project 🤔

It doesn't appear to. Yargs is about the same age, but also very well-tested, heavily-used, and up-to-date. I dunno if I'd even say it's "much bigger" they have roughly the same number of downloads per week on npm (their download-graphs even look similar, which is interesting as a sidenote.)

> Yes, the newer Node is the better ESM support we'll get.
> That's because the entire JavaScript ecosystem is in the transition period of switching from CommonJS to ESM modules.

Hehe, not sure why you are telling me. I am totally aware of the state of js language, and specifically es6 modules. I worked at nodesource, when they were helping to define the spec. Support is pretty solid in 16, and I don't think it's unreasonable as a minimum supported node version, as that is current stable. Anyway, I prefer the built-in module support in 16. They work better, allow top-level async, and have lots of other features. It's lame to have to build it to a lesser format (converted and polyfillled) when node 16 just has support for everything I want. That was my point above, like maybe there is no need to build, because there is no real need for pkg.

**Comment by konsumer** [comment]
That said, I'm not opposed to trying to make it work, if it's not too annoying. I could see very casual users wanting to just download a standalone runtime, and run a simple synth, so I imagine it's a good goal.

**Comment by konsumer** [comment]
I could even see a whole different path. I could do commonjs to require deps, but use `new Function` or `eval` on string from file-read, instead of a dynamic import. If I loaded [esm](https://www.npmjs.com/package/esm) first, it would sort of support modern modules, but still miss other features like top-level `await`. It's doable, but I dunno if it's a good path.

Since I can't see how to do dynamic options with commander, I could also do them myself. This seems to work:

```js
const ar = /[\/-]?((\w+)(?:[=:]("[^"]+"|[^\s"]+))?)(?:\s+|$)/gm
const params = {}
let m
while (m = ar.exec(process.argv.slice(2).join(' '))){
  params[ m[2] ] = parseInt(m[3])
}
console.log(params)
```

```
node test.js --cuttoff=10 --resonance=20
{ cuttoff: 10, resonance: 20 }
```

I guess my main resistance is that it feels like redesigning my thing around pkg, to avoid actual issues pkg has (not yargs, node 16 esm support, dynamic imports, etc.) It may work, but much like swapping out the arg-parser, it seems like big changes for the wrong reason.

**Comment by konsumer** [comment]
[this arg parser](https://github.com/vercel/arg) seems like it could be a better choice for whatever I end up doing with this, if I am trying to build around pkg, because it's made by the same crew. I tested it though, and it has similar problems with parsing arbitrary flags (which I think is a cool way to attach midi to a synth script.)

I tried [nopt](https://www.npmjs.com/package/nopt) and it works alright for dynamic args.

On top of all this, midi requites native modules, which is tricky with pkg, too.

To test these ideas, I used nopt, in [this standalone repo](https://github.com/konsumer/crossaudio-cli-ideas) and used esm module to polyfilll dynamic imports, and it builds fine, but weirdly tries to look in current dir (not relative to the built cli) for the native midi module, so it still fails.

```sh
npm run build

> build
> esbuild --bundle --target=node10 --outdir=./dist --platform=node --out-extension:.js=.cjs ./cli.js && pkg --name=crossaudio --public --out-path dist/ ./dist/cli.cjs


  dist/cli.cjs  476.3kb

⚡ Done in 38ms
> pkg@5.3.0
> Targets not specified. Assuming:
  node14-linux-x64, node14-macos-x64, node14-win-x64

./dist/cli-macos
/snapshot/dist/cli.cjs:12424
      throw err;
      ^

Error: Could not locate the bindings file. Tried:
 → /Users/konsumer/Desktop/argtest/build/midi.node
 → /Users/konsumer/Desktop/argtest/build/Debug/midi.node
 → /Users/konsumer/Desktop/argtest/build/Release/midi.node
 → /Users/konsumer/Desktop/argtest/out/Debug/midi.node
 → /Users/konsumer/Desktop/argtest/Debug/midi.node
 → /Users/konsumer/Desktop/argtest/out/Release/midi.node
 → /Users/konsumer/Desktop/argtest/Release/midi.node
 → /Users/konsumer/Desktop/argtest/build/default/midi.node
 → /Users/konsumer/Desktop/argtest/compiled/14.17.0/darwin/x64/midi.node
 → /Users/konsumer/Desktop/argtest/addon-build/release/install-root/midi.node
 → /Users/konsumer/Desktop/argtest/addon-build/debug/install-root/midi.node
 → /Users/konsumer/Desktop/argtest/addon-build/default/install-root/midi.node
 → /Users/konsumer/Desktop/argtest/lib/binding/node-v83-darwin-x64/midi.node
    at bindings (/snapshot/dist/cli.cjs:12420:13)
    at node_modules/midi/midi.js (/snapshot/dist/cli.cjs:12696:34)
    at __require (/snapshot/dist/cli.cjs:39:44)
    at node_modules/easymidi/index.js (/snapshot/dist/cli.cjs:12755:16)
    at __require (/snapshot/dist/cli.cjs:39:44)
    at Object.<anonymous> (/snapshot/dist/cli.cjs:13130:34)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14) {
  tries: [
    '/Users/konsumer/Desktop/argtest/build/midi.node',
    '/Users/konsumer/Desktop/argtest/build/Debug/midi.node',
    '/Users/konsumer/Desktop/argtest/build/Release/midi.node',
    '/Users/konsumer/Desktop/argtest/out/Debug/midi.node',
    '/Users/konsumer/Desktop/argtest/Debug/midi.node',
    '/Users/konsumer/Desktop/argtest/out/Release/midi.node',
    '/Users/konsumer/Desktop/argtest/Release/midi.node',
    '/Users/konsumer/Desktop/argtest/build/default/midi.node',
    '/Users/konsumer/Desktop/argtest/compiled/14.17.0/darwin/x64/midi.node',
    '/Users/konsumer/Desktop/argtest/addon-build/release/install-root/midi.node',
    '/Users/konsumer/Desktop/argtest/addon-build/debug/install-root/midi.node',
    '/Users/konsumer/Desktop/argtest/addon-build/default/install-root/midi.node',
    '/Users/konsumer/Desktop/argtest/lib/binding/node-v83-darwin-x64/midi.node'
  ]
}
```

It still doesn't work if I copy `node_modules/midi/build/Release/midi.node` into dist, so it just seems like bad handling of native-modules.

**Comment by konsumer** [comment]
I dunno. I give up for a while. I can't seem to quickly get it working, and it's a fairly low priority for me, and it's annoying tweaking on broken tooling, which is kind of one of my least favorite things. If you want a standalone  runtime sooner rather than later, you should work on the build, and I'll happily take a PR. For now, installing it using node tools works fine (ie `npx crossaudio`.)
